

 let banderas = [{
    id: 1,
    bandera: "../images/bandera1.jpg", nombre: "Estonia", capital: "Tallín", continente: "Europa",
    question: " 1) )¿A qué país pertenece esta bandera?",
    a: "Estonia",
    b: "Letonia",
    c: "Lituania",
    url: "../images/bandera1.gif",
    correct: "a",
},
{
    id: 2,
    bandera: "../images/bandera2.jpg", nombre: "Armenia", capital: "Ereván", continente: "Europa",
    question: " 2) )¿A qué país pertenece esta bandera?",
    a: "Georgia",
    b: "Azerbaiyan",
    c: "Armenia",
    url: "../images/bandera2.gif",
    correct: "c",
},
{
    id: 3,
    bandera: "../images/bandera3.jpg", nombre: "Azerbaiyán", capital: "Bakú", continente: "Europa",
    question: " 3) )¿A qué país pertenece esta bandera?",
    a: "Georgia",
    b: "Azerbaiyán",
    c: "Armenia",
    url: "../images/bandera3.gif",
    correct: "b",
},
{
    id: 4,
    bandera: "../images/bandera4.jpg", nombre: "Comoras", capital: "Moroni", continente: "Africa",
    question: " 4) )¿A qué país pertenece esta bandera?",
    a: "Comoras",
    b: "Camerún",
    c: "Sudán del Sur",
    url: "../images/bandera4.gif",
    correct: "a",
},
{
    id: 5,
    bandera: "../images/bandera5.jpg", nombre: "Zimbabue", capital: "Harare", continente: "Africa",
    question: " 5) )¿A qué país pertenece esta bandera?",
    a: "Rep. del Congo",
    b: "Sahara Occidental",
    c: "Zimbabue",
    url: "../images/bandera5.gif",
    correct: "c",
},
{
    id: 6,
    bandera: "../images/bandera6.jpg", nombre: "Suazilandia", capital: "Esuatini", continente: "Africa",
    question: " 6) )¿A qué país pertenece esta bandera?",
    a: "Chad",
    b: "Suazilandia",
    c: "Benín",
    url: "../images/bandera6.gif",
    correct: "b",
},
{
    id: 7,
    bandera: "../images/bandera7.jpg", nombre: "Afganistán", capital: "Kabul", continente: "Asia",
    question: " 7) )¿A qué país pertenece esta bandera?",
    a: "Afganistán",
    b: "Pakistan",
    c: "Irak",
    url: "../images/bandera7.gif",
    correct: "a",
},
{
    id: 8,
    bandera: "../images/bandera8.jpg", nombre: "Bután", capital: "Timbu", continente: "Asia",
    question: " 8) )¿A qué país pertenece esta bandera?",
    a: "Bangladesh",
    b: "Nepal",
    c: "Bután",
    url: "../images/bandera8.gif",
    correct: "c",
},
{
    id: 9,
    bandera: "../images/bandera9.jpg", nombre: "Brunei", capital: "Bandar Seri Begawan", continente: "Asia",
    question: " 9) )¿A qué país pertenece esta bandera?",
    a: "Singapur",
    b: "Brunei",
    c: "Indonesia",
    url: "../images/bandera9.gif",
    correct: "b",
},
{
    id: 10,
    bandera: "../images/bandera10.jpg", nombre: "Las Granadinas", capital: "Kinstown", continente: "America",
    question: " 10) )¿A qué país pertenece esta bandera?",
    a: "San Vicente y Las Granadinas",
    b: "Santa Lucía",
    c: "Barbado",
    url: "../images/bandera10.gif",
    correct: "a",
},
{
    id: 11,
    bandera: "../images/bandera11.jpg", nombre: "Belice", capital: "Belmopán", continente: "America",
    question: " 11) )¿A qué país pertenece esta bandera?",
    a: "Surinam",
    b: "Aruba",
    c: "Belmopán",
    url: "../images/bandera11.gif",
    correct: "c",
},
{
    id: 12,
    bandera: "../images/bandera12.jpg", nombre: "Santa Lucía", capital: "Castries", continente: "America",
    question: " 12) )¿A qué país pertenece esta bandera?",
    a: "Surinam",
    b: "Castries",
    c: "Bonaire",
    url: "../images/bandera12.gif",
    correct: "b",
},
{
    id: 13,
    bandera: "../images/bandera13.jpg", nombre: "Nauru", capital: "Yaren", continente: "Oceania",
    question: " 13) )¿A qué país pertenece esta bandera?",
    a: "Nauru",
    b: "Islas Marshall",
    c: "Tokelau",
    url: "../images/bandera13.gif",
    correct: "a",
},
{
    id: 14,
    bandera: "../images/bandera14.jpg", nombre: "Kiribati", capital: "Tarawa", continente: "Oceania",
    question: " 14) )¿A qué país pertenece esta bandera?",
    a: "Nauru",
    b: "Islas Marshall",
    c: "Kiribati",
    url: "../images/bandera14.gif",
    correct: "c",
},
{
    id: 15,
    bandera: "../images/bandera15.jpg", nombre: "Vanuatu", capital: "Port Vila", continente: "Oceania",
    question: " 15) )¿A qué país pertenece esta bandera?",
    a: "Nueva Caledonia",
    b: "Vanuatu",
    c: "Fiyi",
    url: "../images/bandera15.gif",
    correct: "b",
},
];

export default banderas;